server:
  port: 8092
  servlet:
    context-path: /batch

spring:
  h2:
    console:
      enabled: true
      path: /h2
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          lob:
            non-contextual-creation: true
        format_sql: true
    show-sql: true
  batch:
    job:
      enabled: false

batch:
  job:
    name: "Players-Batch"
    builder:
      name: "Players-Batch-Builder"
    reader:
      name: "Players-Batch-Reader"

  source:
    file:
      name: players.csv